#Stage 1: Builder (golang:1.23-alpine)
FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o agent ./cmd/agent

#Stage 2: Runtime (alpine:latest)
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/agent .

CMD ["./agent"]
